title: Workspace
email: shashibudati@localhost
description: >-
  Blogs, miscellaneous articles in Workspace
baseurl: "/jekyll-template"
url: "https://shashi-budati.github.io/"

twitter_username: jekyllrb
github_username:  jekyll

theme: minima
plugins:
  - jekyll-feed

