title: Workspace
email: shashibudati@localhost
description: >-
  Blogs, miscellaneous articles in Workspace
baseurl: "/jekyll-template"
url: "https://shashi-budati.github.io/"
author: Shashi Budati


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md

paginate: 4
show_excerpts: true
