title: Workspace
email: shashibudati@localhost
description: >-
  Blogs, miscellaneous articles in Workspace
baseurl: "/jekyll-template1"
url: "https://shashi-budati.github.io/"


theme: minima
plugins:
  - jekyll-feed

